version: "3"
services:
    mysql_python:
        image: mysql:5.5.59
        container_name: mysql_python
        environment:
            MYSQL_ROOT_PASSWORD: confluent
            MYSQL_USER: confluent
            MYSQL_PASSWORD: confluent
            MYSQL_DATABASE: connect_test
    python_test:
        image: python_test:latest
        container_name: python_test
        depends_on:
            - mysql_python
        environment:
            KAFKA_CONNECT_HOST: kafka-connect
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            MYSQL_HOST: mysql_python
            MYSQL_PASSWORD: confluent
            ELASTIC_TOPICS: "cigo-jdbc-activities_summary, ratings"
            SINK_TOPICS: "ratings"
networks:
    default:
        external:
            name: cigo-compose_default
