apiVersion: v1
kind: Service
metadata:
  name: access_all
  labels:
    app: access_all
spec:
  type: NodePort 
  ports: 
  - name: "24568" 
    port: 24568
  selector:
    app: access_all
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
   app: access_all
  name: access_all
spec:
  replicas: 1
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: access_all
    spec:
      containers:
      - env:
        - name: KAFKA_CONNECT_HOST
          value: cigo-kafka-connect
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: cigo-schema-registry
        - name: SINK_TOPICS
          value: "activity, mobility_trace, facility, poi, user, user_chooses_route, user_evaluates_activity, user_joins_group, user_uses_app, user_views_activity, user_reward"
        - name: MYSQL_HOST
          value: mysqlpython
        - name: MYSQL_DATABASE
          value: connect_test
        - name: MYSQL_USER
          value: confluent
        - name: MYSQL_PASSWORD
          value: confluent
        image: mytrac/access_all:latest
        imagePullPolicy: Always
        name: access_all
        resources: {}
      restartPolicy: Always
status: {}
