apiVersion: v1
kind: Service
metadata:
  name: mysqlpython
  labels:
    app: mysqlpython
spec:
  #type: LoadBalancer 
  ports:
  - name: "server"
    port: 3306
    targetPort: 3306 
  clusterIP: None
  selector:
    app: mysqlpython 
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: mysqlpython
  name: mysqlpython
spec:
  serviceName: mysqlpython
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqlpython
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: confluent
        - name: MYSQL_USER
          value: confluent
        - name: MYSQL_PASSWORD
          value: confluent
        - name: MYSQL_DATABASE
          value: connect_test
        image: mysql:5.5.59
        args:
            - "--ignore-db-dir=lost+found"
        name: mysqlpython 
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: data 
            mountPath: /var/lib/mysql
      restartPolicy: Always
