apiVersion: v1
kind: Service
metadata:
  name: mysql_python
  labels:
    app: mysql_python
spec:
  #type: LoadBalancer 
  ports:
  - name: "server"
    port: 3306
    targetPort: 3306 
  clusterIP: None
  selector:
    app: mysql_python 
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: mysql_python
  name: mysql_python
spec:
  serviceName: mysql_python
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql_python
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: confluent
        - name: MYSQL_USER
          value: confluent
        - name: MYSQL_PASSWORD
          value: confluent
        - name: MYSQL_DATABASE
          value: connect_test
        image: mysql:5.5.59
        name: mysql_python 
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: data 
            mountPath: /var/lib/mysql
      restartPolicy: Always
