
apiVersion: v1
kind: Service
metadata:
  name: python-test
  labels:
    app: python-test
spec:
  type: NodePort 
  selector:
    app: python-test
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
   app: python-test
  name: python-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-test
    spec:
      containers:
      - env:
        - name: KAFKA_CONNECT_HOST
          value: kafka-connect
        - name: MYSQL_HOST
          value: mysql_python
        - name: MYSQL_PASSWORD
          value: confluent
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schema-registry
        - name: SINK_TOPICS
          value: ratings
        image: python_test:latest
        imagePullPolicy: Always
        name: python_test
        resources: {}
      restartPolicy: Always
status: {}
