apiVersion: v1
kind: Service
metadata:
  name: python-test
  labels:
    app: python-test
spec:
  type: NodePort 
  ports: 
  - name: "24568" 
    port: 24568
  selector:
    app: python-test
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
   app: python-test
  name: python-test
spec:
  replicas: 1
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: python-test
    spec:
      containers:
      - env:
        - name: KAFKA_CONNECT_HOST
          value: cigo-kafka-connect
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: cigo-schema-registry
        - name: SINK_TOPICS
          value: ratings
        - name: SOURCE_TOPICS
          value: employees
        - name: MYSQL_HOST
          value: mysqlpython
        - name: MYSQL_DATABASE
          value: connect_test
        - name: MYSQL_USER
          value: confluent
        - name: MYSQL_PASSWORD
          value: confluent
        image: mytrac/python-test:latest
        imagePullPolicy: Always
        name: python-test
        resources: {}
      restartPolicy: Always
status: {}
